name: Python CI # workflow name

# Trigger the workflow on any push to the main branch or pull request
on:
  push: # event
    branches: 
        - main
  pull_request:
    branches: 
        - main
        # - staging/ production

jobs:
  test:
    runs-on: ubuntu-latest # containers

    steps:
        # Step 1: Checkout the code from the repo
        - name: Checkout code
          uses: actions/checkout@v2

        # Step 2: Set up Python Env
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'
        
        # Step 3: Install dependencies
        # So pip tries to install a package literally named install → “No matching distribution found for install”.
        # Use a multiline run: | block (or &&). While we’re here, let’s bump action versions and add pip caching.
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        # Step 4: Run Tests
        - name: Run tests
          run: pytest
